# Generated by Django 4.0 on 2022-01-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(default='', max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='TradePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=30)),
                ('trade_description', models.TextField()),
                ('feed_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_posts', to='growAPI.feedpost')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_posts', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='WeGrowUser',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='we_grow_user', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='TradePostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_post_comments', to='growAPI.wegrowuser')),
                ('trade_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='growAPI.tradepost')),
            ],
            options={
                'verbose_name_plural': 'TradePostComments',
            },
        ),
        migrations.CreateModel(
            name='FeedPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='growAPI.feedpost')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_post_likes', to='growAPI.wegrowuser')),
            ],
        ),
        migrations.CreateModel(
            name='FeedPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=250)),
                ('feed_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='growAPI.feedpost')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_post_comments', to='growAPI.wegrowuser')),
            ],
            options={
                'verbose_name_plural': 'FeedPostComments',
            },
        ),
        migrations.AddField(
            model_name='feedpost',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to='growAPI.wegrowuser'),
        ),
    ]
